# Generated by Django 3.1.5 on 2022-01-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('Favorite', 'Favorite'), ('Unfavorite', 'Unfavorite')], max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
