# Generated by Django 3.1.5 on 2022-01-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220101_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='rating_type',
        ),
    ]
