# Generated by Django 3.1.5 on 2022-01-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_favorite_rating_type'),
        ('app', '0002_auto_20220101_1843'),
    ]

    operations = [
    ]
