# Generated by Django 3.1.5 on 2022-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ManyToManyField(blank=True, to='app.Project'),
        ),
    ]
