# Generated by Django 3.1.5 on 2022-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220102_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('project', models.ManyToManyField(max_length=50, null=True, to='app.Project')),
            ],
        ),
    ]
