# Generated by Django 4.0 on 2022-02-11 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
