# Generated by Django 3.1.5 on 2022-02-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_comment_date_created_and_more'),
        ('app', '0023_auto_20220212_0011'),
    ]

    operations = [
    ]
